// Code generated by protoc-gen-go.
// source: common.proto
// DO NOT EDIT!

/*
Package proto_struct is a generated protocol buffer package.

It is generated from these files:
	common.proto

It has these top-level messages:
	RoleLoginC2S
	RoleLoginS2C
*/
package proto_struct

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RequestId int32

const (
	RequestId_role_login_c2s RequestId = 1
	RequestId_role_login_s2c RequestId = 2
)

var RequestId_name = map[int32]string{
	1: "role_login_c2s",
	2: "role_login_s2c",
}
var RequestId_value = map[string]int32{
	"role_login_c2s": 1,
	"role_login_s2c": 2,
}

func (x RequestId) Enum() *RequestId {
	p := new(RequestId)
	*p = x
	return p
}
func (x RequestId) String() string {
	return proto.EnumName(RequestId_name, int32(x))
}
func (x *RequestId) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RequestId_value, data, "RequestId")
	if err != nil {
		return err
	}
	*x = RequestId(value)
	return nil
}
func (RequestId) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type RoleLoginC2S struct {
	Account          *string `protobuf:"bytes,1,req,name=account" json:"account,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RoleLoginC2S) Reset()                    { *m = RoleLoginC2S{} }
func (m *RoleLoginC2S) String() string            { return proto.CompactTextString(m) }
func (*RoleLoginC2S) ProtoMessage()               {}
func (*RoleLoginC2S) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RoleLoginC2S) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

type RoleLoginS2C struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RoleLoginS2C) Reset()                    { *m = RoleLoginS2C{} }
func (m *RoleLoginS2C) String() string            { return proto.CompactTextString(m) }
func (*RoleLoginS2C) ProtoMessage()               {}
func (*RoleLoginS2C) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*RoleLoginC2S)(nil), "proto_struct.roleLoginC2s")
	proto.RegisterType((*RoleLoginS2C)(nil), "proto_struct.roleLoginS2c")
	proto.RegisterEnum("proto_struct.RequestId", RequestId_name, RequestId_value)
}

func init() { proto.RegisterFile("common.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 127 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x01, 0x53, 0xf1, 0xc5, 0x25, 0x45,
	0xa5, 0xc9, 0x25, 0x4a, 0x1a, 0x5c, 0x3c, 0x45, 0xf9, 0x39, 0xa9, 0x3e, 0xf9, 0xe9, 0x99, 0x79,
	0xce, 0x46, 0xc5, 0x42, 0x12, 0x5c, 0xec, 0x89, 0xc9, 0xc9, 0xf9, 0xa5, 0x79, 0x25, 0x12, 0x8c,
	0x0a, 0x4c, 0x1a, 0x9c, 0x41, 0x30, 0xae, 0x12, 0x1f, 0x92, 0xca, 0x60, 0xa3, 0x64, 0x2d, 0x63,
	0x2e, 0xce, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0xcf, 0x14, 0x21, 0x21, 0x2e, 0x3e, 0x90,
	0x64, 0x7c, 0x0e, 0x48, 0x36, 0x3e, 0xd9, 0xa8, 0x58, 0x80, 0x11, 0x4d, 0xac, 0xd8, 0x28, 0x59,
	0x80, 0x09, 0x10, 0x00, 0x00, 0xff, 0xff, 0xc0, 0xa8, 0xf2, 0xbf, 0x8b, 0x00, 0x00, 0x00,
}
